service: <service_name>

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
#  environment:
#   MY_VAR: <value>
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan 
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: <arn_table>

#functions:

resources:
  Resources:
    #documentación: https://docs.aws.amazon.com/es_es/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
    BooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: <table_name>
        AttributeDefinitions:
          - AttributeName: <att_name>
            AttributeType: <B | N | S>
        KeySchema:
          - AttributeName: <att_name>
            KeyType: <HASH | RANGE>
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1